# Generated by Django 4.2.14 on 2024-08-16 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date', models.DateField()),
                ('reciept', models.ImageField(upload_to='purchases/')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
                ('supplier_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplieraddress')),
            ],
        ),
    ]
