# Generated by Django 5.1 on 2024-10-05 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_pay_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
