# Generated by Django 5.1 on 2024-10-25 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(100)])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(100)])),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(255)])),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(17)])),
                ('notes', models.CharField(blank=True, max_length=600, null=True, validators=[django.core.validators.MaxLengthValidator(600)])),
            ],
        ),
    ]
