# Generated by Django 5.1 on 2024-10-13 03:49

import asset.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('material', '0001_initial'),
        ('supplier', '0001_initial'),
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('material_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tool_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('asset_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('date', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
                ('supplier_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplieraddress')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseAssetInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('last_maintenance', models.DateField(default=asset.models.AssetInstance.default_last_maintenance)),
                ('next_maintenance', models.DateField(default=asset.models.AssetInstance.default_next_maintenance)),
                ('usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Maintenance Scheduled', 'Maintenance Scheduled'), ('Maintenance Soon', 'Maintenance Soon'), ('Needs Maintenance', 'Needs Maintenance'), ('Out of Service', 'Out Of Service')], default='Good', max_length=21, validators=[django.core.validators.MaxLengthValidator(17)])),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Under Maintance', 'Under Maintenance'), ('Out of Service', 'Out Of Service')], default='Available', max_length=21, validators=[django.core.validators.MaxLengthValidator(17)])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='purchase.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='purchase.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='purchases')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='purchase.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='purchase.purchase')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.tool')),
            ],
        ),
    ]
