# Generated by Django 5.1 on 2024-10-08 19:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchase_tax_alter_purchase_total_and_more'),
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='purchase.purchase')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.tool')),
            ],
        ),
    ]
