# Generated by Django 5.1 on 2024-10-10 01:26

import asset.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(255)])),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rental_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('last_maintenance', models.DateField(default=django.utils.timezone.now)),
                ('next_maintenance', models.DateField(default=asset.models.Asset.default_next_maintenance)),
                ('usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('needs maintenance', 'Needs Maintenance'), ('out of service', 'Out of Service')], default='good', max_length=17, validators=[django.core.validators.MaxLengthValidator(17)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('in use', 'In Use'), ('under maintenance', 'Under Maintance'), ('out of service', 'Out of Service')], default='available', max_length=17, validators=[django.core.validators.MaxLengthValidator(17)])),
                ('notes', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
            ],
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('next_maintenance', models.DateField(default=asset.models.Asset.default_next_maintenance)),
                ('current_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('condition', models.CharField(choices=[('good', 'Good'), ('needs maintenance', 'Needs Maintenance'), ('out of service', 'Out of Service')], default='good', max_length=17, validators=[django.core.validators.MaxLengthValidator(17)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('in use', 'In Use'), ('under maintenance', 'Under Maintance'), ('out of service', 'Out of Service')], default='available', max_length=17, validators=[django.core.validators.MaxLengthValidator(17)])),
                ('notes', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='asset.asset')),
            ],
        ),
    ]
