# Generated by Django 5.1 on 2024-10-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinstance',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='assetinstance',
            constraint=models.UniqueConstraint(fields=('asset', 'serial_number'), name='unique_assetinstance_serial_number'),
        ),
    ]
