# Generated by Django 5.1 on 2024-09-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='customer',
        ),
    ]
