# Generated by Django 5.1 on 2024-09-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderpayment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaterial',
            name='price',
        ),
    ]
