# Generated by Django 5.1 on 2024-10-05 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='callout',
            field=models.DecimalField(choices=[('50.0', 'Standard - $50.00'), ('175.0', 'Emergency - $175.00')], decimal_places=2, default='50.0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=93.0, max_digits=10, validators=[django.core.validators.MinValueValidator(75.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=10, validators=[django.core.validators.MinValueValidator(3.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='labor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='material_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='material_upcharge',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10, validators=[django.core.validators.MinValueValidator(15.0), django.core.validators.MaxValueValidator(75.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='working_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
