# Generated by Django 5.1 on 2024-10-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_ordermodel_orderworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='callout',
            field=models.FloatField(choices=[('50.0', 'Standard - $50.00'), ('175.0', 'Emergency - $175.00')], default='50.0'),
        ),
    ]
