# Generated by Django 5.1 on 2024-10-08 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordertool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertool',
            old_name='quantity',
            new_name='quantity_broken',
        ),
        migrations.AddField(
            model_name='ordertool',
            name='quantity_uesd',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
