# Generated by Django 5.1 on 2024-10-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_quantity_ordertool_quantity_broken_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertool',
            old_name='quantity_uesd',
            new_name='quantity_used',
        ),
    ]
